CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(120) UNIQUE ,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(120) NOT NULL ,
    price NUMERIC(12, 2) NOT NULL ,
    stock INTEGER NOT NULL  
);