spring:
  application:
    name: book-catalog-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/book_catalog}
    username: ${DB_USERNAME:book_app}
    password: TODO-the-same-local-password-used-by-PostgreSQL
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  sql:
    init:
      mode: never
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      accept-float-as-int: false

server:
  address: 127.0.0.1
  port: 8080
